theme: jekyll-theme-slate
name: maschere's blog
markdown: kramdown
permalink: /:year/:month/:day/:title
title: maschere's blog
BASE_PATH : /
kramdown:
  math_engine: mathjax
  input: GFM
  syntax_highlighter: rouge
